# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DJApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DJApp
  pod 'Alamofire', '~> 5.4'
  
  target 'DJAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DJAppUITests' do
    # Pods for testing
  end

end
